# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data_stream.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 3, "", "data_stream.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11\x64\x61ta_stream.proto\x12\ndatastream"\x80\x01\n\tDataPoint\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x31\n\x06\x66ields\x18\x02 \x03(\x0b\x32!.datastream.DataPoint.FieldsEntry\x1a-\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"\x0f\n\rStreamRequest2W\n\x11\x44\x61taStreamService\x12\x42\n\nStreamData\x12\x19.datastream.StreamRequest\x1a\x15.datastream.DataPoint"\x00\x30\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "data_stream_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_DATAPOINT_FIELDSENTRY"]._loaded_options = None
    _globals["_DATAPOINT_FIELDSENTRY"]._serialized_options = b"8\001"
    _globals["_DATAPOINT"]._serialized_start = 34
    _globals["_DATAPOINT"]._serialized_end = 162
    _globals["_DATAPOINT_FIELDSENTRY"]._serialized_start = 117
    _globals["_DATAPOINT_FIELDSENTRY"]._serialized_end = 162
    _globals["_STREAMREQUEST"]._serialized_start = 164
    _globals["_STREAMREQUEST"]._serialized_end = 179
    _globals["_DATASTREAMSERVICE"]._serialized_start = 181
    _globals["_DATASTREAMSERVICE"]._serialized_end = 268
# @@protoc_insertion_point(module_scope)
