# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import data_stream_pb2 as data__stream__pb2

GRPC_GENERATED_VERSION = "1.71.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in data_stream_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class DataStreamServiceStub(object):
    """Service definition"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamData = channel.unary_stream(
            "/datastream.DataStreamService/StreamData",
            request_serializer=data__stream__pb2.StreamRequest.SerializeToString,
            response_deserializer=data__stream__pb2.DataPoint.FromString,
            _registered_method=True,
        )


class DataStreamServiceServicer(object):
    """Service definition"""

    def StreamData(self, request, context):
        """Server streaming RPC"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_DataStreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "StreamData": grpc.unary_stream_rpc_method_handler(
            servicer.StreamData,
            request_deserializer=data__stream__pb2.StreamRequest.FromString,
            response_serializer=data__stream__pb2.DataPoint.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "datastream.DataStreamService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "datastream.DataStreamService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class DataStreamService(object):
    """Service definition"""

    @staticmethod
    def StreamData(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/datastream.DataStreamService/StreamData",
            data__stream__pb2.StreamRequest.SerializeToString,
            data__stream__pb2.DataPoint.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
